# mvnw clean package
FROM openjdk:17-alpine
COPY target/catalogo-1.0.jar /usr/app.jar
EXPOSE 8010
ENTRYPOINT ["java","-jar","/usr/app.jar"]
# CMD ["java","-jar","/usr/app.jar"]
# docker build -t ms-catalogo .
# docker run -d --name ms-catalogo -p 8010:8010 --network microservicios --env SPRING_CLOUD_CONFIG_URI=http://ms-config-server:8888/ ms-catalogo